package com.moneyblue.v2;

import android.app.*;import android.os.*;import android.os.CancellationSignal;import android.hardware.biometrics.BiometricPrompt;import android.content.pm.PackageManager;import android.graphics.drawable.ColorDrawable;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import android.text.*;import org.json.*;import java.io.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
  static int BLUE=Color.rgb(28,104,220), NAVY=Color.rgb(18,31,52), MUTED=Color.rgb(103,116,139), BG=Color.rgb(247,249,253), PALE=Color.rgb(232,241,255), GREEN=Color.rgb(18,157,91), RED=Color.rgb(218,70,75), AMBER=Color.rgb(230,145,25), BORDER=Color.rgb(220,228,240);
  LinearLayout root,content; TextView title; SharedPreferences sp; JSONArray tx=new JSONArray(),tasks=new JSONArray(),accounts=new JSONArray(),categories=new JSONArray(),recurring=new JSONArray(); double budget=50000; String selectedAccount="Cash"; final int BACKUP=42,RESTORE=43;
  int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}
  GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} GradientDrawable outline(int c,int sc,float r){GradientDrawable g=bg(c,r);g.setStroke(dp(1),sc);return g;}
  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BLUE);sp=getSharedPreferences("moneyblue",0);load();seed();applyPalette();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},91);build();if(sp.getBoolean("pinEnabled",false)||sp.getBoolean("bioEnabled",false))unlock();else showHome();}
  void applyPalette(){boolean d=sp.getBoolean("darkMode",false);if(d){BG=Color.rgb(18,22,29);NAVY=Color.rgb(241,245,249);MUTED=Color.rgb(164,174,190);PALE=Color.rgb(27,45,70);BORDER=Color.rgb(55,65,81);}else{BLUE=Color.rgb(28,104,220);NAVY=Color.rgb(18,31,52);MUTED=Color.rgb(103,116,139);BG=Color.rgb(247,249,253);PALE=Color.rgb(232,241,255);BORDER=Color.rgb(220,228,240);GREEN=Color.rgb(18,157,91);RED=Color.rgb(218,70,75);AMBER=Color.rgb(230,145,25);}}
  void load(){try{tx=new JSONArray(sp.getString("tx","[]"));tasks=new JSONArray(sp.getString("tasks","[]"));accounts=new JSONArray(sp.getString("accounts","[]"));categories=new JSONArray(sp.getString("categories","[]"));recurring=new JSONArray(sp.getString("recurring","[]"));budget=sp.getLong("budget",50000);selectedAccount=sp.getString("account","Cash");}catch(Exception ignored){}}
  void save(){sp.edit().putString("tx",tx.toString()).putString("tasks",tasks.toString()).putString("accounts",accounts.toString()).putString("categories",categories.toString()).putString("recurring",recurring.toString()).putString("account",selectedAccount).putLong("budget",(long)budget).apply();}
  void seed(){try{if(accounts.length()==0){accounts.put(new JSONObject().put("name","Cash"));accounts.put(new JSONObject().put("name","Bank"));}if(categories.length()==0){for(String c:new String[]{"Food","Transport","Bills","Shopping","Salary","Health","Entertainment","Other"})categories.put(c);}}catch(Exception ignored){}save();}
  void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);setContentView(root);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(18),dp(8),dp(8),dp(8));bar.setBackgroundColor(BLUE);title=tv("MoneyBlue",21,Color.WHITE);title.setTypeface(null,1);bar.addView(title,new LinearLayout.LayoutParams(0,dp(56),1));TextView bell=tv("◦",28,Color.WHITE);bell.setGravity(Gravity.CENTER);bell.setOnClickListener(v->showNotifications());bar.addView(bell,new LinearLayout.LayoutParams(dp(48),dp(56)));TextView gear=tv("⚙",24,Color.WHITE);gear.setGravity(Gravity.CENTER);gear.setOnClickListener(v->showSettings());bar.addView(gear,new LinearLayout.LayoutParams(dp(48),dp(56)));root.addView(bar);ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(16),dp(16),dp(24));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));nav();}
  void nav(){LinearLayout n=new LinearLayout(this);n.setPadding(dp(4),dp(5),dp(4),dp(7));n.setBackgroundColor(Color.WHITE);String[] a={"⌂\nHome","↕\nMoney","▣\nCalendar","◔\nReports","✓\nTasks"};for(String s:a){TextView b=tv(s,11,MUTED);b.setGravity(Gravity.CENTER);String key=s.substring(s.indexOf('\n')+1);b.setOnClickListener(v->{if(key.equals("Home"))showHome();else if(key.equals("Money"))showTransactions();else if(key.equals("Calendar"))showCalendar();else if(key.equals("Reports"))showReports();else showTasks();});n.addView(b,new LinearLayout.LayoutParams(0,dp(58),1));}root.addView(n);}
  void clear(String h){content.removeAllViews();title.setText(h);}
  TextView head(String s){TextView t=tv(s,19,NAVY);t.setTypeface(null,1);t.setPadding(0,dp(7),0,dp(11));return t;}
  TextView btn(String s){TextView b=tv(s,14,Color.WHITE);b.setGravity(Gravity.CENTER);b.setTypeface(null,1);b.setBackground(bg(BLUE,13));return b;}
  TextView obtn(String s){TextView b=tv(s,14,BLUE);b.setGravity(Gravity.CENTER);b.setBackground(outline(Color.WHITE,BLUE,13));return b;}
  EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setTextSize(14);e.setPadding(dp(12),dp(7),dp(12),dp(7));return e;}
  String money(double x){return "PKR "+String.format(Locale.US,"%,.0f",x);} double sum(String type){double x=0;for(int i=0;i<tx.length();i++){JSONObject o=tx.optJSONObject(i);if(o!=null&&type.equals(o.optString("type")))x+=o.optDouble("amount");}return x;} double income(){return sum("income");} double expense(){return sum("expense");}
  void showHome(){clear("MoneyBlue");double in=income(),ex=expense(),net=in-ex;LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(20),dp(16),dp(20),dp(16));card.setBackground(bg(BLUE,20));TextView k=tv("TOTAL BALANCE",11,Color.WHITE);k.setAlpha(.8f);card.addView(k);TextView v=tv(money(net),30,Color.WHITE);v.setTypeface(null,1);card.addView(v);card.addView(tv("Income  "+money(in)+"     •     Expenses  "+money(ex),12,Color.WHITE));content.addView(card,new LinearLayout.LayoutParams(-1,dp(135)));LinearLayout row=new LinearLayout(this);row.setPadding(0,dp(12),0,dp(4));quick(row,"＋","Income",()->transactionDialog("income",false));quick(row,"−","Expense",()->transactionDialog("expense",false));quick(row,"✓","Task",this::taskDialog);quick(row,"▤","Report",this::showReports);content.addView(row);TextView acc=tv("  Wallet: "+selectedAccount+"   ▾",13,BLUE);acc.setGravity(Gravity.CENTER_VERTICAL);acc.setBackground(bg(PALE,12));acc.setOnClickListener(vv->accountPicker());content.addView(acc,new LinearLayout.LayoutParams(-1,dp(44)));content.addView(head("This month"));LinearLayout stats=new LinearLayout(this);metric(stats,"Income",money(in),GREEN);metric(stats,"Spent",money(ex),RED);metric(stats,"Budget left",money(Math.max(0,budget-ex)),BLUE);content.addView(stats);double pct=budget<=0?0:Math.min(1,ex/budget);TextView bl=tv("Budget  "+money(ex)+" / "+money(budget)+"   ("+(int)(pct*100)+"%)",12,MUTED);content.addView(bl);ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(100);pb.setProgress((int)(pct*100));content.addView(pb,new LinearLayout.LayoutParams(-1,dp(8)));content.addView(head("Spending overview"));content.addView(new ChartView(this),new LinearLayout.LayoutParams(-1,dp(190)));content.addView(head("Recent activity"));if(tx.length()==0)empty("No transactions yet","Use the buttons above to add your first transaction.");else for(int i=0;i<Math.min(4,tx.length());i++)transactionCard(tx.optJSONObject(i),false);content.addView(head("Tasks"));int shown=0;for(int i=0;i<tasks.length()&&shown<3;i++){JSONObject o=tasks.optJSONObject(i);if(o!=null&&!o.optBoolean("done")){taskCard(o);shown++;}}if(shown==0)empty("You're all caught up","No open tasks.");}
  void quick(LinearLayout r,String icon,String name,final Runnable run){LinearLayout q=new LinearLayout(this);q.setOrientation(LinearLayout.VERTICAL);q.setGravity(Gravity.CENTER);TextView i=tv(icon,21,BLUE);i.setGravity(Gravity.CENTER);i.setBackground(bg(PALE,16));q.addView(i,new LinearLayout.LayoutParams(dp(48),dp(42)));TextView n=tv(name,11,MUTED);n.setGravity(Gravity.CENTER);q.addView(n);q.setOnClickListener(v->run.run());r.addView(q,new LinearLayout.LayoutParams(0,dp(70),1));}
  void metric(LinearLayout r,String n,String v,int c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(3),0,dp(3),0);x.addView(tv(n,11,MUTED));TextView z=tv(v,14,c);z.setTypeface(null,1);x.addView(z);r.addView(x,new LinearLayout.LayoutParams(0,dp(50),1));}
  void empty(String a,String b){TextView t=tv(a+"\n"+b,13,MUTED);t.setPadding(dp(3),dp(4),0,dp(14));content.addView(t);}
  void transactionCard(JSONObject o,boolean clickable){if(o==null)return;LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(10),dp(8),dp(10),dp(8));c.setBackground(outline(Color.WHITE,BORDER,13));LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);TextView n=tv(o.optString("title","Transaction"),14,NAVY);n.setTypeface(null,1);l.addView(n);l.addView(tv(o.optString("category","Other")+"  •  "+o.optString("account","Cash")+"  •  "+o.optString("date",""),10,MUTED));c.addView(l,new LinearLayout.LayoutParams(0,dp(58),1));boolean inc="income".equals(o.optString("type"));TextView a=tv((inc?"+":"−")+money(o.optDouble("amount")),14,inc?GREEN:RED);a.setTypeface(null,1);c.addView(a);if(clickable)c.setOnClickListener(v->transactionActions(o));content.addView(c,new LinearLayout.LayoutParams(-1,dp(70)));}
  void showTransactions(){clear("Money");EditText s=field("Search title, category or account");content.addView(s,new LinearLayout.LayoutParams(-1,dp(50)));TextView add=btn("＋  Add transaction");add.setOnClickListener(v->chooseAdd());content.addView(add,new LinearLayout.LayoutParams(-1,dp(46)));LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);TextWatcher w=new TextWatcher(){public void beforeTextChanged(CharSequence a,int b,int c,int d){}public void onTextChanged(CharSequence a,int b,int c,int d){renderTx(list,a.toString());}public void afterTextChanged(Editable e){}};s.addTextChangedListener(w);renderTx(list,"");}
  void renderTx(LinearLayout list,String q){list.removeAllViews();for(int i=0;i<tx.length();i++){JSONObject o=tx.optJSONObject(i);if(o==null)continue;String hay=(o.optString("title")+" "+o.optString("category")+" "+o.optString("account")).toLowerCase();if(q.isEmpty()||hay.contains(q.toLowerCase())){int old=content.indexOfChild(list);transactionCardInto(list,o,true);}}}
  void transactionCardInto(LinearLayout parent,JSONObject o,boolean clickable){if(o==null)return;LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(10),dp(7),dp(10),dp(7));c.setBackground(outline(Color.WHITE,BORDER,12));LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);TextView n=tv(o.optString("title","Transaction"),14,NAVY);n.setTypeface(null,1);l.addView(n);l.addView(tv(o.optString("category","Other")+"  •  "+o.optString("account","Cash")+"  •  "+o.optString("date",""),10,MUTED));c.addView(l,new LinearLayout.LayoutParams(0,dp(58),1));boolean inc="income".equals(o.optString("type"));TextView a=tv((inc?"+":"−")+money(o.optDouble("amount")),14,inc?GREEN:RED);a.setTypeface(null,1);c.addView(a);c.setOnClickListener(v->transactionActions(o));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(70));p.bottomMargin=dp(6);parent.addView(c,p);}
  void showCalendar(){clear("Calendar");Calendar cal=Calendar.getInstance();TextView month=head(new SimpleDateFormat("MMMM yyyy",Locale.US).format(cal.getTime()));content.addView(month);DatePicker dpick=new DatePicker(this);dpick.setCalendarViewShown(false);dpick.init(cal.get(Calendar.YEAR),cal.get(Calendar.MONTH),cal.get(Calendar.DAY_OF_MONTH),(v,y,m,d)->calendarDay(String.format(Locale.US,"%04d-%02d-%02d",y,m+1,d)));content.addView(dpick,new LinearLayout.LayoutParams(-1,dp(310)));content.addView(head("Selected day"));calendarDay(new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(cal.getTime()));}
  void calendarDay(String day){while(content.getChildCount()>3)content.removeViewAt(3);boolean f=false;for(int i=0;i<tx.length();i++){JSONObject o=tx.optJSONObject(i);if(o!=null&&day.equals(o.optString("date"))){transactionCard(o,true);f=true;}}if(!f)empty("No transactions","Nothing recorded on this date.");}
  void showReports(){clear("Reports");double in=income(),ex=expense();content.addView(head("Financial overview"));report("Income",money(in),GREEN);report("Expenses",money(ex),RED);report("Net",money(in-ex),BLUE);content.addView(head("Spending by category"));content.addView(new ChartView(this),new LinearLayout.LayoutParams(-1,dp(230)));HashMap<String,Double> m=new HashMap<>();for(int i=0;i<tx.length();i++){JSONObject o=tx.optJSONObject(i);if(o!=null&&"expense".equals(o.optString("type"))){String c=o.optString("category","Other");m.put(c,m.getOrDefault(c,0.0)+o.optDouble("amount"));}}for(String k:new TreeSet<>(m.keySet())){TextView x=tv(k+"     "+money(m.get(k)),13,NAVY);x.setPadding(dp(5),dp(9),0,dp(9));content.addView(x);}}
  void report(String n,String v,int c){LinearLayout x=new LinearLayout(this);x.setGravity(Gravity.CENTER_VERTICAL);x.setPadding(dp(14),0,dp(14),0);x.setBackground(bg(Color.WHITE,12));TextView a=tv(n,13,MUTED);x.addView(a,new LinearLayout.LayoutParams(0,dp(58),1));TextView b=tv(v,17,c);b.setTypeface(null,1);x.addView(b);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(64));p.bottomMargin=dp(7);content.addView(x,p);}
  void showTasks(){clear("Tasks & Notes");TextView add=btn("＋  New task / note");add.setOnClickListener(v->taskDialog());content.addView(add,new LinearLayout.LayoutParams(-1,dp(46)));LinearLayout filter=new LinearLayout(this);filter.setPadding(0,dp(8),0,dp(5));TextView all=obtn("All"),open=obtn("Open"),done=obtn("Done");filter.addView(all,new LinearLayout.LayoutParams(0,dp(42),1));filter.addView(open,new LinearLayout.LayoutParams(0,dp(42),1));filter.addView(done,new LinearLayout.LayoutParams(0,dp(42),1));content.addView(filter);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);Runnable r=()->{list.removeAllViews();for(int i=0;i<tasks.length();i++)taskCardInto(list,tasks.optJSONObject(i),0);};all.setOnClickListener(v->r.run());open.setOnClickListener(v->{list.removeAllViews();for(int i=0;i<tasks.length();i++){JSONObject o=tasks.optJSONObject(i);if(o!=null&&!o.optBoolean("done"))taskCardInto(list,o,0);}});done.setOnClickListener(v->{list.removeAllViews();for(int i=0;i<tasks.length();i++){JSONObject o=tasks.optJSONObject(i);if(o!=null&&o.optBoolean("done"))taskCardInto(list,o,0);}});r.run();}
  void taskCard(JSONObject o){if(o!=null){LinearLayout fake=new LinearLayout(this);taskCardInto(content,o,0);}}
  void taskCardInto(LinearLayout parent,JSONObject o,int mode){if(o==null)return;LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(8),dp(5),dp(8),dp(5));c.setBackground(outline(Color.WHITE,BORDER,12));CheckBox ch=new CheckBox(this);ch.setChecked(o.optBoolean("done"));ch.setOnCheckedChangeListener((b,v)->{try{o.put("done",v);save();}catch(Exception ignored){}});c.addView(ch);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);TextView n=tv(o.optString("title","Task"),14,NAVY);n.setTypeface(null,1);l.addView(n);String sub=o.optString("note","");String rem=o.optString("reminder","");l.addView(tv(sub+(rem.isEmpty()?"":"  •  ⏰ "+rem),11,MUTED));c.addView(l,new LinearLayout.LayoutParams(0,dp(62),1));c.setOnLongClickListener(v->{taskActions(o);return true;});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(70));p.bottomMargin=dp(6);parent.addView(c,p);}
  void chooseAdd(){new AlertDialog.Builder(this).setTitle("Quick add").setItems(new String[]{"Income","Expense","Task / Note","Recurring expense","Recurring income"},(d,w)->{if(w==0)transactionDialog("income",false);else if(w==1)transactionDialog("expense",false);else if(w==2)taskDialog();else transactionDialog(w==3?"expense":"income",true);}).show();}
  LinearLayout form(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(5),0,dp(5),0);return l;}
  void transactionDialog(String type,boolean repeat){LinearLayout l=form();EditText n=field("Title");LinearLayout amountRow=new LinearLayout(this);amountRow.setGravity(Gravity.CENTER_VERTICAL);EditText a=field("Amount (PKR)");a.setInputType(2|8192);TextView calc=obtn("Calculator");calc.setOnClickListener(v->calculator(a));amountRow.addView(a,new LinearLayout.LayoutParams(0,dp(52),1));amountRow.addView(calc,new LinearLayout.LayoutParams(dp(110),dp(46)));EditText c=field("Category");EditText ac=field("Account");l.addView(n);l.addView(amountRow);l.addView(c);l.addView(ac);EditText f=null;if(repeat){f=field("Repeat: Daily / Weekly / Monthly");l.addView(f);}final EditText ff=f;new AlertDialog.Builder(this).setTitle(repeat?"Recurring transaction":(type.equals("income")?"Add income":"Add expense")).setView(l).setPositiveButton("Save",(d,w)->{if(repeat)saveRecurring(type,n,a,c,ac,ff);else saveTx(type,n,a,c,ac);}).setNegativeButton("Cancel",null).show();}
  void saveTx(String type,EditText n,EditText a,EditText c,EditText ac){try{double amt=Double.parseDouble(a.getText().toString());if(amt<=0)throw new Exception();JSONObject o=new JSONObject();o.put("type",type);o.put("title",n.getText().toString().trim().isEmpty()?"Transaction":n.getText().toString().trim());o.put("amount",amt);o.put("category",c.getText().toString().trim().isEmpty()?"Other":c.getText().toString().trim());o.put("account",ac.getText().toString().trim().isEmpty()?selectedAccount:ac.getText().toString().trim());o.put("date",new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()));tx.put(0,o);save();showHome();}catch(Exception e){toast("Enter a valid amount");}}
  void saveRecurring(String type,EditText n,EditText a,EditText c,EditText ac,EditText f){try{double amt=Double.parseDouble(a.getText().toString());JSONObject o=new JSONObject();o.put("type",type);o.put("title",n.getText().toString());o.put("amount",amt);o.put("category",c.getText().toString());o.put("account",ac.getText().toString());o.put("frequency",f.getText().toString().trim().isEmpty()?"Monthly":f.getText().toString());recurring.put(0,o);save();toast("Recurring item saved");showHome();}catch(Exception e){toast("Enter a valid amount");}}
  void taskDialog(){LinearLayout l=form();EditText n=field("Task / note title");EditText d=field("Details / note");EditText r=field("Reminder: yyyy-MM-dd HH:mm (optional)");l.addView(n);l.addView(d);l.addView(r);new AlertDialog.Builder(this).setTitle("New task / note").setView(l).setPositiveButton("Save",(x,w)->{try{JSONObject o=new JSONObject();o.put("title",n.getText().toString().trim().isEmpty()?"Untitled":n.getText().toString().trim());o.put("note",d.getText().toString());o.put("reminder",r.getText().toString());o.put("done",false);long at=parseReminder(r.getText().toString());o.put("reminderAt",at);tasks.put(0,o);save();if(at>System.currentTimeMillis())scheduleReminder(o,at);showTasks();}catch(Exception ignored){}}).setNegativeButton("Cancel",null).show();}
  void taskActions(JSONObject o){new AlertDialog.Builder(this).setTitle(o.optString("title")).setItems(new String[]{"Edit","Mark complete/open","Delete"},(d,w)->{if(w==0)editTask(o);else if(w==1){try{o.put("done",!o.optBoolean("done"));save();showTasks();}catch(Exception ignored){}}else{removeObject(tasks,o);save();showTasks();}}).show();}
  void editTask(JSONObject o){LinearLayout l=form();EditText n=field("Title");n.setText(o.optString("title"));EditText d=field("Details");d.setText(o.optString("note"));EditText r=field("Reminder");r.setText(o.optString("reminder"));l.addView(n);l.addView(d);l.addView(r);new AlertDialog.Builder(this).setTitle("Edit task").setView(l).setPositiveButton("Save",(x,w)->{try{o.put("title",n.getText().toString());o.put("note",d.getText().toString());o.put("reminder",r.getText().toString());save();showTasks();}catch(Exception ignored){}}).show();}
  void transactionActions(JSONObject o){new AlertDialog.Builder(this).setTitle(o.optString("title")).setItems(new String[]{"Delete","Duplicate"},(d,w)->{if(w==0)removeObject(tx,o);else if(w==1)tx.put(new JSONObject(o.toString()));save();showTransactions();}).show();}
  void removeObject(JSONArray a,JSONObject target){for(int i=0;i<a.length();i++)if(a.opt(i)==target){a.remove(i);break;}}
  void accountPicker(){ArrayList<String> names=new ArrayList<>();for(int i=0;i<accounts.length();i++)names.add(accounts.optJSONObject(i).optString("name"));names.add("＋ Add account");new AlertDialog.Builder(this).setTitle("Choose wallet").setItems(names.toArray(new String[0]),(d,w)->{if(w==names.size()-1)addAccount();else{selectedAccount=names.get(w);save();showHome();}}).show();}
  void addAccount(){EditText e=field("Account / wallet name");new AlertDialog.Builder(this).setTitle("New account").setView(e).setPositiveButton("Save",(d,w)->{try{if(!e.getText().toString().trim().isEmpty())accounts.put(new JSONObject().put("name",e.getText().toString().trim()));save();showHome();}catch(Exception ignored){}}).show();}
  void showSettings(){clear("Settings");content.addView(head("MoneyBlue V4"));TextView dm=obtn(sp.getBoolean("darkMode",false)?"Switch to light mode":"Switch to dark mode");dm.setOnClickListener(v->{sp.edit().putBoolean("darkMode",!sp.getBoolean("darkMode",false)).apply();recreate();});content.addView(dm,new LinearLayout.LayoutParams(-1,dp(46)));TextView a=btn("Manage accounts");a.setOnClickListener(v->accountPicker());content.addView(a,new LinearLayout.LayoutParams(-1,dp(46)));TextView b=obtn("Set monthly budget");b.setOnClickListener(v->budgetDialog());content.addView(b,new LinearLayout.LayoutParams(-1,dp(46)));TextView c=obtn("Backup data (JSON)");c.setOnClickListener(v->backup());content.addView(c,new LinearLayout.LayoutParams(-1,dp(46)));TextView d=obtn("Restore backup");d.setOnClickListener(v->restore());content.addView(d,new LinearLayout.LayoutParams(-1,dp(46)));TextView e=obtn("Export transactions (CSV)");e.setOnClickListener(v->exportCsv());content.addView(e,new LinearLayout.LayoutParams(-1,dp(46)));TextView bio=obtn(sp.getBoolean("bioEnabled",false)?"Disable biometric unlock":"Enable biometric unlock");bio.setOnClickListener(v->{if(Build.VERSION.SDK_INT>=28){sp.edit().putBoolean("bioEnabled",!sp.getBoolean("bioEnabled",false)).apply();toast(sp.getBoolean("bioEnabled",false)?"Biometric unlock enabled":"Biometric unlock disabled");showSettings();}else toast("Biometric unlock requires Android 9+");});content.addView(bio,new LinearLayout.LayoutParams(-1,dp(46)));TextView p=obtn(sp.getBoolean("pinEnabled",false)?"Change / disable PIN":"Enable app PIN");p.setOnClickListener(v->pinDialog());content.addView(p,new LinearLayout.LayoutParams(-1,dp(46)));content.addView(tv("\nWhite + blue • Offline-first • PKR\nVersion 4",12,MUTED));}
  void budgetDialog(){EditText e=field("Monthly budget in PKR");e.setText(String.valueOf((long)budget));new AlertDialog.Builder(this).setTitle("Monthly budget").setView(e).setPositiveButton("Save",(d,w)->{try{budget=Double.parseDouble(e.getText().toString());save();showHome();}catch(Exception x){toast("Invalid budget");}}).show();}
  void showNotifications(){new AlertDialog.Builder(this).setTitle("Reminders").setMessage("MoneyBlue keeps your task reminder text with each task. Android notification scheduling can be enabled in a later build when you choose exact reminder behavior.").setPositiveButton("OK",null).show();}
  void backup(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"MoneyBlue-V3-backup.json");startActivityForResult(i,BACKUP);}
  void restore(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,RESTORE);}
  @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;try{if(r==BACKUP){JSONObject all=new JSONObject();all.put("tx",tx);all.put("tasks",tasks);all.put("accounts",accounts);all.put("categories",categories);all.put("recurring",recurring);all.put("budget",budget);OutputStream o=getContentResolver().openOutputStream(d.getData());o.write(all.toString(2).getBytes("UTF-8"));o.close();toast("Backup saved");}else{InputStream in=getContentResolver().openInputStream(d.getData());ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buf=new byte[4096];int n;while((n=in.read(buf))>0)out.write(buf,0,n);in.close();JSONObject all=new JSONObject(new String(out.toByteArray(),"UTF-8"));tx=all.optJSONArray("tx");tasks=all.optJSONArray("tasks");accounts=all.optJSONArray("accounts");categories=all.optJSONArray("categories");recurring=all.optJSONArray("recurring");budget=all.optDouble("budget",50000);save();showHome();toast("Backup restored");}}catch(Exception e){toast("Could not process file");}}
  void exportCsv(){StringBuilder s=new StringBuilder("Date,Type,Title,Category,Account,Amount\n");for(int i=0;i<tx.length();i++){JSONObject o=tx.optJSONObject(i);s.append(csv(o.optString("date"))).append(',').append(csv(o.optString("type"))).append(',').append(csv(o.optString("title"))).append(',').append(csv(o.optString("category"))).append(',').append(csv(o.optString("account"))).append(',').append(o.optDouble("amount")).append('\n');}Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/csv");i.putExtra(Intent.EXTRA_TEXT,s.toString());startActivity(Intent.createChooser(i,"Export CSV"));}
  String csv(String s){return "\""+s.replace("\"","\"\"")+"\"";}
  void pinDialog(){if(sp.getBoolean("pinEnabled",false)){new AlertDialog.Builder(this).setTitle("App PIN").setItems(new String[]{"Disable PIN","Set new PIN"},(d,w)->{if(w==0)sp.edit().putBoolean("pinEnabled",false).apply();else setPin();showSettings();}).show();}else setPin();}
  void setPin(){EditText e=field("4-6 digit PIN");e.setInputType(2);new AlertDialog.Builder(this).setTitle("Set PIN").setView(e).setPositiveButton("Save",(d,w)->{String p=e.getText().toString();if(p.matches("\\d{4,6}"))sp.edit().putBoolean("pinEnabled",true).putString("pin",p).apply();else toast("PIN must be 4-6 digits");}).show();}
  void unlock(){if(sp.getBoolean("bioEnabled",false)&&Build.VERSION.SDK_INT>=28){BiometricPrompt prompt=new BiometricPrompt.Builder(this).setTitle("Unlock MoneyBlue").setSubtitle("Use your fingerprint or device biometric").setNegativeButton("Use PIN",getMainExecutor(),(d,w)->pinUnlock()).build();prompt.authenticate(new CancellationSignal(),getMainExecutor(),new BiometricPrompt.AuthenticationCallback(){public void onAuthenticationSucceeded(BiometricPrompt.AuthenticationResult r){runOnUiThread(()->showHome());}public void onAuthenticationFailed(){toast("Biometric not recognized");}public void onAuthenticationError(int c,CharSequence e){if(c!=10)toast(e.toString());}});}else pinUnlock();}
  void pinUnlock(){EditText e=field("Enter PIN");e.setInputType(2);new AlertDialog.Builder(this).setTitle("MoneyBlue locked").setView(e).setCancelable(false).setPositiveButton("Unlock",(d,w)->{if(e.getText().toString().equals(sp.getString("pin","")))showHome();else{toast("Wrong PIN");pinUnlock();}}).show();}
  void calculator(EditText target){EditText e=field("Example: 1200+350*2");new AlertDialog.Builder(this).setTitle("Amount calculator").setView(e).setPositiveButton("Use result",(d,w)->{try{target.setText(String.valueOf(eval(e.getText().toString())));}catch(Exception x){toast("Invalid expression");}}).setNegativeButton("Cancel",null).show();}
  double eval(String x){x=x.replaceAll("\\s","");java.util.Stack<Double> nums=new java.util.Stack<>();java.util.Stack<Character> ops=new java.util.Stack<>();for(int i=0;i<x.length();){if(Character.isDigit(x.charAt(i))||x.charAt(i)=='.'){int j=i+1;while(j<x.length()&&(Character.isDigit(x.charAt(j))||x.charAt(j)=='.'))j++;nums.push(Double.parseDouble(x.substring(i,j)));i=j;}else{char op=x.charAt(i++);while(!ops.empty()&&prec(ops.peek())>=prec(op))apply(nums,ops.pop());ops.push(op);}}while(!ops.empty())apply(nums,ops.pop());return nums.pop();}
  int prec(char c){return c=='+'||c=='-'?1:2;}void apply(java.util.Stack<Double> n,char o){double b=n.pop(),a=n.pop();n.push(o=='+'?a+b:o=='-'?a-b:o=='*'?a*b:a/b);}
  long parseReminder(String s){try{return new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).parse(s).getTime();}catch(Exception e){return -1;}}
  void scheduleReminder(JSONObject o,long at){try{AlarmManager am=(AlarmManager)getSystemService(ALARM_SERVICE);Intent i=new Intent(this,ReminderReceiver.class);i.putExtra("title",o.optString("title"));PendingIntent pi=PendingIntent.getBroadcast(this,o.hashCode(),i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);}catch(Exception ignored){}}
  void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
  class ChartView extends View {Paint p=new Paint(1); ChartView(Context c){super(c);p.setTypeface(Typeface.create("sans",0));setBackground(bg(Color.WHITE,16));}protected void onDraw(Canvas c){super.onDraw(c);double total=expense();HashMap<String,Double> m=new HashMap<>();for(int i=0;i<tx.length();i++){JSONObject o=tx.optJSONObject(i);if(o!=null&&"expense".equals(o.optString("type"))){String k=o.optString("category","Other");m.put(k,m.getOrDefault(k,0.0)+o.optDouble("amount"));}}if(m.isEmpty()){p.setColor(MUTED);p.setTextSize(dp(13));c.drawText("Add expenses to see your spending chart",dp(18),getHeight()/2f,p);return;}ArrayList<Map.Entry<String,Double>> es=new ArrayList<>(m.entrySet());Collections.sort(es,(a,b)->Double.compare(b.getValue(),a.getValue()));int max=Math.min(5,es.size());float y=dp(25);for(int i=0;i<max;i++){Map.Entry<String,Double> e=es.get(i);p.setColor(NAVY);p.setTextSize(dp(11));c.drawText(e.getKey(),dp(14),y+dp(11),p);float w=(float)((getWidth()-dp(120))*e.getValue()/Math.max(total,1));p.setColor(BLUE);c.drawRoundRect(dp(92),y,dp(92)+w,y+dp(18),dp(8),dp(8),p);p.setColor(MUTED);p.setTextSize(dp(10));c.drawText(money(e.getValue()),dp(98)+w,y+dp(13),p);y+=dp(31);}}}
  public static class ReminderReceiver extends BroadcastReceiver {public void onReceive(Context c,Intent i){String ch="moneyblue_reminders";NotificationManager nm=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26)nm.createNotificationChannel(new NotificationChannel(ch,"MoneyBlue reminders",NotificationManager.IMPORTANCE_DEFAULT));Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(c,ch):new Notification.Builder(c);b.setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle("MoneyBlue reminder").setContentText(i.getStringExtra("title")).setAutoCancel(true);nm.notify((int)System.currentTimeMillis(),b.build());}}

}
